tuf-spec.md
The sections 2.1.1 and 2.1.2 are nested one layer below the section header 2.1, which makes sense. However, this indentation isn't consistent with sections 2.1.3 - 2.1.5. This change simply updates the indentation to keep all the role sections consistent.
=> Fix indentation for subsections 2.1.3 - 2.1.5

tuf-spec.md
Fixes #10.
This pull request revises section **1.5.2** so that consistent phrasing (An attacker cannot..) is used when describing the malicious actions/attacks disallowed by the framework.
=> Revise section 1.5.2

tuf-spec.md
Make it clear that delegation is whitelisting, and revocation is
removal from the whitelist. Prior text implied a blacklist
("`signing new metadata that indicates the delegated role is no
longer trusted`")
Also, strip an extraneous word ("developer" in "Delegated developer
roles"), fixing #13.
=> Clarify wording in 2.1.2 Targets role re. revocation

tuf-spec.md
This pull request replaces instances of `digest.rolename.ext` with `version_number.rolename.ext.`  The specification previously prepended digest/hashes to metadata filenames.  It now uses version numbers for metadata files, and digests/hashes for target files.
[This issue was reported by @trishankatdatadog.]
Unrelated: Some paragraphs are edited so that their lines do not exceed a length of 80 characters.
Signed-off-by: Vladimir Diaz <vladimir.v.diaz@gmail.com>
=> Replace instances of digest.rolename.ext

tuf-spec.md
It looks like an extra newline and bullet point was accidentally introduced in section 5.3.1. This removes it, and re-wraps the section.
=> Fix a typo in section 5.3.1

tuf-spec.0.9.txt
The 0.9 tuf spec in section 4.6 mentions that "version" is included in the signed portion of timestamp.json, but was missing from the example file. This adds it.
Feel free to reject this patch if you want to leave 0.9 as a historical document.
=> 0.9 timestamp example was missing "version"

tuf-spec.md
According to #42, the spec should explicitly state that the ed25519 public key, and the target hash values are hex encoded values, since that is used by the majority of tuf implementations.
Closes #42
=> Use hex encoding is used for ed25519 and target hashes

tuf-spec.md
@JustinCappos in https://github.com/heartsucker/rust-tuf/pull/207#issuecomment-521453860 recommended that the timestamp role should only allow a reference to the snapshot metadata, and no other roles.
=> timestamp must only refer to the snapshot metadata

tuf-spec.md
In https://github.com/theupdateframework/tuf/pull/679, the python tuf project forbade leading path separators due to surprising behavior joining target and delegated paths, since Python in particular has the following surprising behavior:
```
>>> os.path.join("/foo", "/bar")
'/bar'
```
This PR updates the spec to recommend against using leading path separators in targets.json, and removes their use from the examples. Does this change look acceptable, and is "should not" be the correct phrase, or can this be the more strict "must not"?
=> Recommend against leading path separators

tuf-spec.md
The first removed link is supposed to provide additional reasons for the need of consistent snapshots. Besides pointing to a removed anchor in an outdated and unmaintained version of pep 485, the spec already lists the same reasons that are mentioned in the pep.
The second link points to a different (existing) section in the same outdated document, but gives implementation details that IMO don't need to be in the spec. If wished we can update the second link instead of removing it.
=> Remove links to outdated pep 458

tuf-spec.md
It looks like the sample Key IDs in the 1.0 spec were not updated to the TUF 1.0 algorithm. For example:
```python
>>> key_meta = { "keytype": "ed25519", "keyval": { "public": "72378e5bc588793e58f81c8533da64a2e8f1565c1fcc7f253496394ffc52542c" } }
>>> key_update_data = securesystemslib.formats.encode_canonical(key_meta)
>>> digest_object = securesystemslib.hash.digest("sha256")
>>> digest_object.update(key_update_data.encode('utf-8'))
>>> digest_object.hexdigest()
'1a2b4110927d4cba257262f614896179ff85ca1f1353a41b5224ac474ca71cb4'
>>>
>>> key_meta = { "keytype": "ed25519", "scheme": "ed25519", "keyval": { "public": "72378e5bc588793e58f81c8533da64a2e8f1565c1fcc7f253496394ffc52542c" } }
>>> key_update_data = securesystemslib.formats.encode_canonical(key_meta)
>>> digest_object = …
```
=> Fix keyids in the 1.0 spec

tuf-spec.md
theupdateframework/specification#51 updated the format of the `"spec_version"` field in any tuf metadata to strictly require a string that conforms to the Semantic Versioning 2.0.0 standard.
This PR updates the metadata examples in the specification accordingly.
=> Adopt semver for "spec_version" in sample metadata

tuf-spec.md
According to @JustinCappos in #31, the root.json is no longer needed in the snapshot metadata, because the workflow will already have updated the root metadata before the snapshot metadata is fetched.
In addition, section 5.6 of the Mercury paper describes a need for delegations to contain hashes in order to protect against malicous mirrors that may substitute one version of the delegated metadata with another. This cannot be detected without hashing of these files.
Closes #31
=> Remove root, add delegation hashes to the snapshot metadata

tuf-spec.md
This extends the spec to clarify that when searching for the key that
signed a delegated role, that key should only be found in the delegating
target, and not any other role in the delegation chain. This incorporates
language suggested by lukpueh in #58, and the definition of the keys
field from [TAP 3](#57).
Closes #58
=> delegated targets are authorized by keys in the delegating target roles

README.rst
Use restructured text instead of html syntax for links in acknowledgement section in README.rst. 
Here is how the document used to render [before](https://github.com/theupdateframework/specification/blob/0cddec0a60f95f06d2e23ebadbd876eeb62c1df3/README.rst) and how it renders [now (correctly)](https://github.com/lukpueh/specification/blob/511a15393289219456440182e952d5b39bf0af5e/README.rst).
=> Fix link markup in README.rst

tuf-spec.md
Fixes #56 
Updates an outdated paragraph in section 6.1 that explained how root keys are rotated by backwards-verifying signatures from the latest root file available on the repository back to the latest root file available
on the client.
The correct (new) workflow, which is also described in step 1 of the client application workflow of section 5, performs verification in a forward-directed manner, i.e. starting at the latest root on the client and going forward to the latest root on the repo.
=> Fix inconsistency in root key migration paragraph

tuf-spec.md
Remove not fully accurate phrase in the `HASHES` definition in section “4.5. File formats: targets.json and delegated target roles” of the spec.
Contrary to that phrase, `HASHES` is an unconditionally mandatory value under each `TARGETPATH` for top-level targets and all delegated targets roles:
```
{ TARGETPATH : {
"length" : LENGTH,
"hashes" : HASHES,
("custom" : { ... }) }
, ...
}
```
It seems like this accidentally slipped through our review in the recent (and actually unrelated) #47. (cc @erickt, @trishankatdatadog).
=> Fix (delegated) targets metadata HASHES definition

tuf-spec.md
Closes #63 
In addition to recommending the omission of leading directory separators, this commit adds a recommendation for forward slashes as preferred directory separators in TARGETPATH and PATHPATTERN.
The rationale is that a TARGETPATH needs to be concatenated with a mirror's base URL, and as such it might yield unexpected behavior with non standardized paths. Same goes for Unix shell-style pattern matching of target paths using PATHPATTERN.
As suggested by @erickt this commit adds a reference to the "path-relative-URL string" definition from the WHATWG URL spec as the preferred TARGETPATH style.
This commit also switches to using the term "directory separator" instead of the prior used "path separator" to disambiguate from characters that separate paths (e.g. colon on Unix).
=> Update TARGETPATH and PATHPATTERN recommendations

tuf-spec.md
According to @JustinCappos in #68, clients should persist the timestamp metadata to disk after it has been validated.
Closes #68
=> Clients should write the timestamp to disk

tuf-spec.md
In the client application workflow, remove rollback attack check for top-level targets file, which is (1) redundant and (2) prevents recovery from a fast-forward attack.
(1) rollback attacks, via serving older versions of targets or top-level targets than the previously trusted versions, are already prevented by step 3.3.3 of the client workflow, where version numbers of targets and delegated targets in the new snapshot metadata are asserted to be greater than those in the prior trusted snapshot metadata. This, in combination with the 4.1 check that asserts that hashes and version of the actual targets metadata match the ones in the new trusted snapshot, makes another version number check, i.e the one removed in this PR, obsolete.
(2) fast-forward attack recovery, as described in 1.9, …
=> Remove problematic targets rollback attack check

.travis.yml, README.rst, check_release.py
Fixes #73 
- Add gitflow-based version- and release management instructions to the Versioning section of the README.
- Add links to "latest stable", "current draft", "new changes since latest stable" and "release history" of the specification in the header of the README document.
(Note that the version number of the latest stable version of the specification is no longer shown in the README, which eliminates the need to update the README with every new release.)
- Add script to run on Travis upon a GitHub pull request, that checks that versioning- and release management rules are followed, and configure travis accordingly.
Reviewers may focus on the changes in `README.rst`. 
The `check_release.py`-script and `.travis.yml`-configuration are only there to help us follow the version/release …
=> Add specification versioning- and release management instructions and checks

check_release.py
A minor tweak to `check_release.py` to only suggest that the submitter tag a release and synch the draft branch with master when merging changes from the draft branch.
=> Only suggest a release in check_release.py fo merges from draft

tuf-spec.md
The specification claims that it adheres to TAP 3 and TAP 4, which is not the case. TAP 3 requires changes to the existing metadata format (prepared in #57) and TAP 4 adds a new metadata file (map.json), which is not yet mentioned in the specification (issue described in #88).
As agreed in the TUF community meeting on Dec 10, 2019, we remove TAP 3 and TAP 4 (adherence claims) for a formal 1.0.0 release and will add TAP 4 in version 1.1.x and TAP 3 in version 2.x.x.
(see [meeting notes about "Versioning" ](https://groups.google.com/forum/#!msg/theupdateframework/oPTliXibT_4/0tJ_POLGAwAJ))
*NOTE: Let's ignore the version management strategy and checker results for this PR. As agreed in the meeting (see notes above) this will be the last change before we formally release TUF 1.0.0. After …
=> Remove TAP 3 + 4 adherence claim

tuf-spec.md
A read-through of the spec made me question the definition of METAFILES for `snapshot.json`.
In step 3 of the client application detailed workflow the spec states that the client download 
> "up to the number of bytes specified in the timestamp metadata file"
yet the description of METAFILES for `snapshot.json` suggests the object behaves the same as METAFILES in `timestamp.json` where LENGTH is optional.
As @erickt raised a similar concern in #38 here's a pull request to try and clarify.
=>  Clarify timestamp.json METAFILES format

tuf-spec.md
Update section "4.5. File formats: targets.json and delegated target roles" to reflect metadata format introduced by [TAP 3](https://github.com/theupdateframework/taps/blob/master/tap3.md).
Note that TAP 3 is not implemented in the reference implementation, which claims to be spec 1.0.0 conformant!
=> Adopt TAP 3 multi-role delegations metadata format

tuf-spec.md
**Issue:** Inconsistency in snapshot role definition throughout the specification
Snapshot role definition in 2.1.3 and 3.1.2 states that:
> The snapshot role signs a metadata file that provides information about the latest version of all of the other metadata on the repository  (excluding the timestamp file, discussed below).
While the detailed file formats description in 4.4 says: 
>  It MUST list the version numbers of the top-level targets metadata and all delegated targets metadata. 
From the latter, we understand that both `root.json` and `timestamp.json` are excluded from the snapshot which is also shown in the example files.
**Proposed changes:** 
Update snapshot role definition in 2.1.3 and 3.1.2 to match the  file format description (4.4) and explicitly state which metadata …
=> Update snapshot role definition

tuf-spec.md
Some minor changes to try and improve clarity of the spec, specifically:
* make it clear that SPEC_VERSION, VERSION and EXPIRES exist in each file format and are the same as is described for root.json
* Define LENGTH for TARGETSOBJECT
=> Minor clarifications

tuf-spec.md
Addresses #101 by replacing the JSON requirement with a statement that any data format may be used.
This pr keeps the canonical JSON examples in the specification, but adds a clarification about filenames to support non-json metadata.
This change is backwards compatible, so I propose it as a patch to the current version of the specification.
=> Replace strict JSON requirement with a flexible requirement

tuf-spec.md
This updates section 5.2.2 to also state that when updating the `timestamp` role, we should also check to make sure new `timestamp` role's `snapshot` version is greater than or equal to the trusted `timestamp`'s `snapshot` version.
This is an important check when initializing a TUF database. For example, say we had the following TUF metadata:
* `root`, which has signed all the below metadata
* `snapshot` version 1, which points at a target with a compromised package
* `snapshot` version 2, which points at a target with a fixed package
* `timestamp` version 2, which points at snapshot version 2
Lets say an attacker has stolen the `timestamp` keys, they could forge a new `timestamp` role which points at `snapshot` version 1. In the normal case where we have a fully initialized TUF database …
=> Timestamp rollback check should also check for snapshot rollback

tuf-spec.md
This shares the same justification for removal as #65. Step 3.3.1 was made redundant by #106, which modified the workflow to add 2.2.2, where updating the timestamp will also check if the new timestamp contains a snapshot version that is less than the trusted snapshot version.
This, in combination with the 3.1 check that asserts hashes and version of the actual snapshot metadata match the ones in the new trusted timestamp, make another version check, i.e, the one removed in this commit, obsolete.
=> Remove 2nd snapshot rollback attack check

tuf-spec.md
I think we should remove slow retrieval attacks from 1.5.2. Goals to protect against specific attacks. I've included details in the commit message but the tl;dr is that:
1. AFAICT nothing in the _specification_ protects against these attacks
2. implementing protections against slow retrieval attacks has a high complexity for implementers which is not met by sufficient need
3. ownership of the network/download stack, in order to protect against slow retrieval attacks, is not something that clients are willing to give up (i.e. pip has thoroughly tested download code that they'd like to keep using)
=> Remove slow retrieval attacks from protections

tuf-spec.md
TUF-1.0.5 requires clients to write metadata to disk before it was validated, but this has multiple downsides:
* The metadata may have corrupted during the download. By writing it before validation, we prevent the client from using the local store.
* This could allow an attacker to persist malicious metadata that exploit a parser bug across reboots.
Instead, this patch changes the spec to explicitly write the metadata after validation to avoid these issues.
=> Persist metadata to local store after validation

tuf-spec.md
* Switch many cases of must, optional to MUST, OPTIONAL to match RFC-2119.
* Change Freeze-Attack to use MUST instead of "should".
* Update links to https://theupdateframework.io
* Fix some typos.
* Standardize convention from "(if any)" to ", if any," since that was more common.
* Switch from "Check signatures" to "Check or an arbitrary software attack".
=> Clean up language

tuf-spec.md
In section 5.3.1 and section 5.4.1 of the spec, the first part of verifying a new snapshot, targets, and delegated targets role requires checking the new role's version number before we've checked that these new roles were signed by the root role. This exposes TUF clients to potential parser bugs which allows an attacker to potentially compromise the system.
For example, consider a man-in-the-middle attacker that has a parser bug which allows for executing arbitrary code, such as [CVE-2017-18349]. An attacker could exploit this in a few manners:
1. [POUF-1] inlines the metadata signatures in with the role JSON metadata file. While snapshot, targets, and delegated targets can have their hashes listed in trusted metadata (and thus be validated before parsing), the timestamp role must be …
=> Checking version after verifying signatures

tuf-spec.md
Fix a cross-reference and use consistent capitalisation for all titles.
I put the version and date bump in a separate patch, as it is not clear to me whether it is required for these very minor tweaks.
=> Minor clean-ups

tuf-spec.md
Minor tweak of the description of the custom field of TARGETPATH objects to explicitly state that the value is an object which is opaque to the framework.
Fixes #50
=> Minor change to clarify that 'custom' is an object

GOVERNANCE.md, MAINTAINERS.md
In-line with what is discussed in #130 here's a first stab at documenting our change review process. I don't know whether 5 business days is long enough a contemplation period, or whether the term "business days" is clear enough. I'd very much welcome feedback on those aspects, as well as the rest of the proposal.
In order to ensure it's clear _who_ will be doing the review, I've also added a `MAINTAINERS.md` listing the consensus builder and active TAP editors. Hopefully we can link to this document from [TAP 1](https://github.com/theupdateframework/taps/blob/master/tap1.md) so that it's clear to participants in the TAP process who the TAP Editors are.
Significant inspiration was taken from SPIFFE's [GOVERNANCE.md](https://github.com/spiffe/spiffe/blob/master/GOVERNANCE.md)
=> Document change review process

tuf-spec.md
Addresses: #113 
Per the discussion between @erickt and @trishankatdatadog in Slack, this PR introduces a fixed notion of time to the client workflow. The client should store the time at the beginning of the update and use it for comparing expiration times throughout the detailed client workflow, so long as the session has not lasted longer than the re-signing period of the timestamp metadata.
=> Introduce a fixed notion of time for the duration of the update cycle

tuf-spec.md
The text makes it clear that both "length" and "hashes" are optional and
not dependent on each other. The object format seems to imply that
both should not be included at the same time: DELEGATIONS uses the same
construct to express exactly that.
Express more clearly that the attributes are not dependent on each
other.
---
Fixes #134
=> Fix METAFILES definition to match the text

tuf-spec.md
Add a description of POUFs, and a pointer to TAP 11 to add official support for TAP 11 to the specification.
supersedes #120.
=> Add TAP 11 to the specification

tuf-spec.md
When introducing the fixed notion of time I also added "workflow maximum duration T" to allow for some slack in the expiration time, but the way T is combined with the fixed notion of time results in what should be a valid expiration being classed as expired and TUF stopping the update for a possible freeze attack. There are more details in the commit message.
Thanks to @trishankatdatadog for spotting this inconsistency.
The simplest way to clean this up was to remove the fixed time slack, T. Especially as the purpose of the PR was to introduce the fixed notion of time, the slack was feature creep.
However, I'd be interested in hearing from TAP editors on the following:
* Is the slack time (T) a useful notion to re-introduce (along with updated descriptions of the freeze attack checks)? …
=> Fix freeze attack checks after the introduction of workflow maximum duration (by removing workflow maximum duration?)

.gitignore, Makefile, check_release.py, header.include, tuf-spec.md
This PR lays the groundwork for #121 and is based on the excellent initial work by @erickt.
You can see a rendered version of the bikesheded specification document here: https://joshuagl.github.io/specification/
The major changes in this PR are:
* Convert tuf-spec.md to Bikeshed Flavoured Markdown (bfm) in 2be515a
* Start adopting some of the bfm features in 0713382 and c714c04. __NOTE__ until this point the content of the spec is unchanged, all of the changes are stylistic
* Changes the wording of some of the object field definitions, to better match the new layout and style, in 211ffbf
* Misc. tweaks in remaining commmits
I've been pleasantly surprised by how readable the [raw document](https://raw.githubusercontent.com/joshuagl/specification/joshuagl/bikeshed-initial/tuf-spec.md) still …
=> Initial conversion of the specification to bikeshed flavoured Markdown

tuf-spec.md
This PR renames the "Usage" section to "Repository operations" and moves the section on "Consistent snapshots" to be a subsection of "Repository operations" alongside the existing subsection on "Key management and migration".
Then, most notable, in 4ccd04c it adds a new subsection to "Repository operations" to describe the workflow for updating repository metadata when adding targets to the repository, or updating existing targets on the repository. This lifts heavily from the [text in PEP 458](https://github.com/python/peps/blob/master/pep-0458.txt#L1008-L1019) describing the repository workflow, fixing #105.
=> Consolidate repository related content, describe repository workflow for adding targets

tuf-spec.md
This is the change from #141 rebased after the bikeshed conversion.
=> Remove multi-role vestigial

tuf-spec.md
Addresses #173 by emphasising that the shell style wildcard matching of the specification is glob-like, and therefore a path separator in a path should not be matched by a wildcard in the `PATHPATTERN`.
=> Clarify PATHPATTERN wildcards are glob-like

tuf-spec.md
I'm making explicit some requirements that I _think_ are already implicit in the spec:
* role names in delegations must be unique
* keyids in signatures must be unique
I guess the high level question is: is this really a "bug fix" or should it be handled as a change in spec? I think it's a fix that clarifies what is already the obvious/logical/safe implementation of the spec, but especially on the role names I can see someone could maybe argue otherwise.
=> Add notes on uniqueness of keyids and role names

.vscode/settings.json, tuf-spec.md
https://github.com/theupdateframework/specification/issues/163
Addressing this, specify that implementers should preserve unknown key-value pairs and include them in calculating hashes or verifying signatures.
I would like to add examples here, but it feels like an awkward place if the format hasn't been defined at this point in the spec.
Signed-off-by: Asra Ali <asraa@google.com>
=> Add guidance about unknown fields

tuf-spec.md
This pr merges changes from #157, #158, and #162 into one for an easier review process and
merging (considering we have to bump the version on each merge)
and closes https://github.com/theupdateframework/specification/issues/156.
This pr makes three changes
- make `delegations` optional
- make `consistent_snapshot` optional
- clarify which of `paths` and `path_hash_prefixes` can be used and when
Nowhere in the spec, we clarify that `delegations` is an optional field
in the targets, metadata file which is implied by the file format scheme showed for targets [here](https://theupdateframework.github.io/specification/latest/index.html#file-formats-targets).
From chapter [6.2.1](https://theupdateframework.github.io/specification/latest/index.html#writing-consistent-snapshots) in the tuf …
=> Clarify optional attributes

.github/workflows/pr.yml
Use bikeshed to build the spec as part of the PR workflow to try and prevent breaking changes being merged.
=> Build spec during PR workflow

tuf-spec.md
An attempt to fix #138 
Does this look good @tedbow?
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> Explain why we check hashes before signatures

tuf-spec.md
* Match how metadata and target filenames are referred to in the detailed
client workflow, i.e. filename.ext -> FILENAME.EXT
* Remove suggestion to write a version of the root metadata without a
version prefix. We only ever look for version-prefixed version of root
metadata.
Fixes #184
=> Clean up "Writing consistent snapshots" section

tuf-spec.md
A few minor clean-up/clarification patches based on some recent reading and discussion of the spec:
1. consistent capitalisation of TAP
2. clarify that mirrors are optional
3. briefly describe the requirement for uniquely addressable targets in the repository layout section
=> A round of clean-up/clarifications

tuf-spec.md
In section [5.3. Update the root role](https://theupdateframework.github.io/specification/v1.0.26/#update-root) the specification suggests, in multiple steps (5.3.4, 5.3.5 and 5.3.10) that should the client fail to verify the updated root metadata the downloaded data should be discarded, the error reported, and
> On the next update cycle, begin at step § 5.3 Update the root role and version N of the root metadata file.
This directive only makes sense if the client application continues
running between update cycles and therefore still has initial trusted root
metadata loaded and a fixed update start time recorded.
For at least python-tuf and go-tuf this is not how the update workflow is
implementated.
Avoid confusion by removing the recommendation to start at 5.3 on the next
update cycle …
=> Remove ambiguity in update root after a failed attempt

Roadmap.md
The roadmap was copied from a Hackmd created during the TUF community meeting.
We might be able to delete the housekeeping portion before merging this.
=> Add TUF roadmap

tuf-spec.md
The client workflow has a set of version comparisons rules for how
to update metadata files. The following PR addresses the differences
coming from the fact that when updating not all metadata files should
be treated equally.
Fixes #207 and is related to #114 
Notes:
- **root** should be updated only when there's a newer version
- **timestamp** should be updated only when there's a newer version AND the referenced **snapshot** version is not less than the one in the already trusted timestamp
- **snapshot** should be updated only when its version is the same as the one referenced in the trusted timestamp AND the version of the referenced **targets** metadata (incl. delegated targets files) is equal or newer than the ones in the trusted snapshot.
- **targets** should be updated only when …
=> Update metadata version comparison rules in client workflow

.github/workflows/check-latest-spec-version.yml, README.rst
The following adds a workflow that can be used by projects that want to keep track and be notified when there's a new version of the TUF specification. 
In case there's a newer version, it will file an issue against the project with several links, like the currently supported version, and a comparison showing what's changed. Here's an example of the issue it will create - 
**Title:** 
> TUF specification has a new version - v1.0.30
**Body:** 
> Hey, it seems there's a newer version of the TUF specification - [v1.0.30](https://github.com/theupdateframework/specification/blob/v1.0.30/tuf-spec.md)
> 
> The version which [rdimitrov/python-tuf](https://github.com/rdimitrov/python-tuf) state it supports is - [v1.0.29](https://github.com/theupdateframework/specification/blob/v1.0.29/tuf-spec.md) …
=> feat: add reusable workflow for autofilling an issue when there's a new TUF version

.github/workflows/draft.yml, .github/workflows/pr.yml, .github/workflows/release.yml, requirements.txt
Replaces more laborious use of actions/cache in GitHub workflows.
Fixes #193
Closes #244
Signed-off-by: Lukas Puehringer <lukas.puehringer@nyu.edu>
=> Use new actions/setup-python builtin caching

.github/workflows/release.yml
Since 70f167f the setup-python action restores a cache based on the fingerprint of requirements.txt, therefore we must ensure a copy of that file exists before we setup Python. This order of events requires the first action to be checkout to clone the repository.
Signed-off-by: Joshua Lock <jlock@vmware.com>
=> Clone repository before setting up Python

tuf-spec.md
Key formats are a recurring source of confusion (see https://github.com/secure-systems-lab/securesystemslib/issues/513, https://github.com/theupdateframework/specification/issues/201, and https://github.com/secure-systems-lab/securesystemslib/issues/308). Do we specify key formats, or simply record those used by the reference implementation? 
The current status is unclear, so this PR attempts to:
1. clarify that the spec only documents the key formats used by the reference implementation
2. recommend against redefining the formats documented in the spec
3. renames the "ecdsa-sha2-nistp256" key format to "ecdsa", per the reference implementation (https://github.com/secure-systems-lab/securesystemslib/pull/267)
The above changes are included in a single commit …
=> Clarify current state of key formats in the spec

.github/workflows/release.yml
Something changed in our GitHub Actions environment (either the platform itself or our organisation's default permissions) since the last specification release such that the build and publish workflow has failed for the most recent change.
This PR is the simplest fix, adding the required permissions for the workflow to succeed.
=> Fix specification builds

tuf-spec.md
Add some additional text to each "Check for an arbitrary software attack" section describing threshold computation, in an attempt to help TUF implementers avoid falling into the trap of a naive implementation of threshold counting resulting in incorrect, security affecting, behaviour. 
Further enhance this guidance by recommending, in "File formats", that the signatures list only contain one signature per keyid.
This kind of detail will be easier to add in a much clearer way once we rewrite the workflow to call out to subsections (https://github.com/theupdateframework/specification/issues/121), however I wanted to add this information as soon as possible because we continue to see implementers falling into the same trap:
* [Incorrect threshold signature …
=> Add more text describing threshold computation
